### PR TITLE
Syllable structure

### LINKED ISSUE #2: Syllable should include more linguistic data
Though the `Syllable` has useful properties, it should have **linguistic** [properties of syllables](https://en.wikipedia.org/wiki/Syllable#Components) as well. Suggestions:

```typescript
Syllable.onset: string | null
Syllable.nucleus: string
Syllable.coda: string | null
```

### Syllable.onset

The overwhelming majority of Hebrew syllables have an `onset`. Though the aleph or ayin may not be considered an onset in Modern Hebrew, they were in Biblical, and orthographically function like an `onset`.

The only syllable that won't have `onset` is a word-initial shureq (e.g. וּמֶלֶךְ [u. 'mε. lεk])

In Biblical Hebrew, there are no medial consonants in the `onset`; that is, there are no consonant clusters (i.e. CCV or CCVC types). The only exception is for the numeral שְׁתַּיִם and its various forms.

### Syllable.nucleus

Every syllable must have a `nucleus` (i.e. vowel). A vocal shewa is a nucleus

### Syllable.coda

A `coda` is optional. A final qamet-he or qamets-aleph would not count as a coda; these would be of the syllable type CV, but a he with a mappiq would be a coda—it would be a syllable type of CVC.

### PR DESCRIPTION
**Pull request by m-yac**
*NB: This PR builds off #113 so should not be merged until the former is reviewed and/or merged.*

This PR adds `onset`, `nucleus`, and `coda` methods to the `Syllable` class and appropriate tests to `syllable.test.ts`. These methods are exactly as described in #2 (with the exception that they return `""` instead of `null`).

This PR also adds `codaWithGemination`, which includes gemination of the subsequent syllable in the coda. This is inspired by my comment in https://github.com/charlesLoder/hebrew-transliteration/discussions/68.

Note that currently the onset of the first syllable of שְׁתַּיִם is not `"שְׁתּ"`, as it ought to be, since this library syllabifies שְׁתַּיִם as `["שְׁ", "תַּ", "יִם"]`.

Resolves #2

### CODE REVIEW

**Comment by charlesLoder** [comment]
I'm looking over this, and it's freaking amazing!

I'm gonna spend some time with it before merging just so I can grok it a bit.

File: src/syllable.ts [hunk 1]
```diff
@@ -240,4 +240,128 @@ export class Syllable extends Node<Syllable> {
...
+  /**
+   * @returns the structure of the Syllable, i.e. the syllable's onset, nucleus, and coda.
+   * - The onset is any initial consonant of the syllable - present in every syllable except those containing a except word-initial shureq or a furtive patah.
+   * - The nucleus is the vowel of the syllable - present in every syllable and containing its {@link vowel} (with any materes lecticonis) or a shureq.
+   * - The coda is all final consonants of the syllable - not including any matres lecticonis, and including the onset of the subsequent syllable if the subsequent syllable is geminated and the `withGemination` argument is `true`.
+   *
+   * @param withGemination If this argument is `true`, include gemination of the next syllable's onset in this syllable's coda.
+   *
+   * ```typescript
+   * const text: Text = new Text("מַדּוּעַ");
```
Comment (charlesLoder) [inline src/syllable.ts:253]: That's a perfect example word

**Review by charlesLoder — APPROVED** [review]
Awesome!
